name: 'Python License Check'
description: 'Checks the licenses of Python dependencies and sends notifications if restricted licenses are found'
inputs:
  slack_webhook_url:
    description: 'Slack webhook URL for sending notifications'
    required: true
  allow_list:
    description: 'Regex pattern for allowed licenses'
    default: '(MIT|BSD|ISC|Apache|CC0)'
runs:
  using: 'composite'
  steps:
    - name: 'Check out Code'
      uses: actions/checkout@v2

    - name: 'Set up Python'
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: 'Install dependencies'
      run: pip install -r requirements.txt
      shell: bash

    - name: 'Install license checker library'
      run: pip install pip-licenses
      shell: bash

    - name: 'Run license check on dependencies'
      run: pip-licenses --format=csv --with-urls --no-version --output-file=licenses.csv
      shell: bash

    - name: 'Check for restricted licenses'
      run: |
        chmod +x ${{ github.action_path }}/license_check.sh
        ${{ github.action_path }}/license_check.sh licenses.csv "${{ inputs.allow_list }}"
      shell: bash

    - name: 'Show all license info'
      run: |
        chmod +x ${{ github.action_path }}/show_license.sh
        ${{ github.action_path }}/show_license.sh licenses.csv
      shell: bash

    - name: 'Format output to JSON'
      run: |
        chmod +x ${{ github.action_path }}/create_json.sh
        ${{ github.action_path }}/create_json.sh invalid.csv
      shell: bash

    - name: 'POST JSON'
      run: |
        json_data=$(cat slack_message.json)
        escaped_json_data=$(echo "$json_data" | jq -c .)
        curl -X POST -H 'Content-type: application/json' --data "$escaped_json_data" ${{ inputs.slack_webhook_url }}
      shell: bash
